### ISSUE TITLE
Installation error in NetBeans 8.2

### ISSUE THREAD

**Issue by lsoares** [fundacionjala/oblivion-netbeans-plugin#6]
Is is a known error?
![image](https://cloud.githubusercontent.com/assets/674045/25300090/b182fefe-26ff-11e7-84d0-29a511b30664.png)
won't let click "Next"

It's related with Oblivion only; it happens when that one is selected alone also.

**Comment by mgarnica** [comment]
Hi Luis,

Yes, this was a known error, we already fixed and validated it against NetBeans IDE 8.2 (Build 201609300101), could you try downloading the nbms from the following locations and try to install them manually?

https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion-gradle.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion-parsing.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-apexdoc.nbm

please, let us know if this fixed the problem for you

**Comment by lsoares** [comment]
Yes, downloading directly seemed to allow its installation! Thanks!
