### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by elmerhd** [fundacionjala/oblivion-netbeans-plugin#7]
![image](https://user-images.githubusercontent.com/29664616/29909814-709387e4-8ddc-11e7-8cf2-70d2b0ea292a.png)

**Comment by mgarnica** [comment]
Hi elmerhd,

are you using NetBeans IDE 8.2?, if so could you try downloading the nbms from the following locations and try to install them manually?

https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion-gradle.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion-parsing.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-oblivion.nbm
https://dl.bintray.com/fundacionjala/enforce-dist/1.1/org-fundacionjala-apexdoc.nbm

please, let us know if this fixed the problem for you

**Comment by elmerhd** [comment]
it worked, thanks
